### ISSUE TITLE
Upadate and Delete button not working

### ISSUE THREAD

**Issue by alexdisoza007** [RajshekharHoratti/Basic-CRUD-Table-With-File-Upload-#1]
Hi,
You have done a great work, I was looking for a CRUD table with FILE UPLOAD but I wasn't getting any so thanks for the share and I found that the update and the delete button are not working so can you please check it out.

Thanks
Alex

**Comment by RajshekharHoratti** [comment]
Hi Alex,
Ya it was missing in the previous version.
I Updated the code so you can check it out and let me know if you face any problem.

Thanks
Rajshekhar Horatti
